spring:
  application:
    name: "vlute-document-management"

  datasource:
    url: "jdbc:mysql://localhost:3306/vlute-document-management"
    username: "root"
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: "mysql"
    show-sql: true
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
